// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoE8s4Jsy2-E94zniFkGGlt7ersdm4eJo',
    appId: '1:562333502674:web:17f9824e71935dcc50710b',
    messagingSenderId: '562333502674',
    projectId: 'mobilepaymenttool',
    authDomain: 'mobilepaymenttool.firebaseapp.com',
    storageBucket: 'mobilepaymenttool.appspot.com',
    measurementId: 'G-JKG2VXJ64W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3J6Tmcz-JAHhrL_Fn9l8ZB8XF-xjxCNg',
    appId: '1:562333502674:android:88dafd795668ee7850710b',
    messagingSenderId: '562333502674',
    projectId: 'mobilepaymenttool',
    storageBucket: 'mobilepaymenttool.appspot.com',
  );
}
